#!/usr/bin/env bash
set -euo pipefail

PROJECT=${1:-}
SPRINT=${2:-}
if [[ -z "$PROJECT" || -z "$SPRINT" ]]; then
  echo "Usage: $0 <client|server> <sprint-number>"
  exit 2
fi

OUT_DIR="$PROJECT/sprints"
mkdir -p "$OUT_DIR"
OUT_FILE="$OUT_DIR/sprint-${SPRINT}-report.md"

echo "Generating sprint report for $PROJECT sprint $SPRINT -> $OUT_FILE"
echo "# Sprint ${SPRINT} Report ($PROJECT)" > "$OUT_FILE"
echo "Generated: $(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> "$OUT_FILE"
echo >> "$OUT_FILE"

if [[ "$PROJECT" == "client" ]]; then
  echo "## Build" >> "$OUT_FILE"
  echo '\nRun: `cmake -S client -B client/build -DCMAKE_BUILD_TYPE=Debug && cmake --build client/build --target camera_client`' >> "$OUT_FILE"
  echo >> "$OUT_FILE"
  echo '```' >> "$OUT_FILE"
  cmake -S client -B client/build -DCMAKE_BUILD_TYPE=Debug 2>&1 | tee -a "$OUT_FILE"
  cmake --build client/build --target camera_client 2>&1 | tee -a "$OUT_FILE"
  echo '```' >> "$OUT_FILE"

  echo >> "$OUT_FILE"
  echo "## Tests" >> "$OUT_FILE"
  echo '\nRun: `ctest --test-dir client/build -V`' >> "$OUT_FILE"
  echo >> "$OUT_FILE"
  echo '```' >> "$OUT_FILE"
  ctest --test-dir client/build -V 2>&1 | tee -a "$OUT_FILE"
  echo '```' >> "$OUT_FILE"

elif [[ "$PROJECT" == "server" ]]; then
  echo "## Build" >> "$OUT_FILE"
  echo '\nRun: `gradle build` (or `./gradlew build` if present)' >> "$OUT_FILE"
  echo >> "$OUT_FILE"
  echo '```' >> "$OUT_FILE"
  if [[ -x "server/gradlew" ]]; then
    (cd server && ./gradlew build) 2>&1 | tee -a "$OUT_FILE"
  else
    (cd server && gradle build) 2>&1 | tee -a "$OUT_FILE" || true
  fi
  echo '```' >> "$OUT_FILE"

else
  echo "Unknown project: $PROJECT" >&2
  exit 3
fi

echo >> "$OUT_FILE"
echo "## Notes" >> "$OUT_FILE"
echo "- Report generated by scripts/save_sprint_report.sh" >> "$OUT_FILE"

echo "Report written to $OUT_FILE"
